### ISSUE TITLE
text hard to read when color is dark.

### ISSUE THREAD

**Issue by walterbender** [sugarlabs/hittheballs-activity#16]
If the background color of the ball is dark, it can be difficult to read the numbers -- dark on dark. Maybe we can either put a limit on how dark the colors get or switch polarity of the text if the color is dark; or maybe the easiest solution, use a drop shadow with white text and a black drop shadow.

**Comment by Hybried8** [comment]
Hi!

I think I've come up with a solution

**Comment by chimosky** [comment]
Fixed in #7.
